### PR TITLE
Vendoring update

### PR DESCRIPTION
**Pull request by jvehent**
For review and merge if everything looks legit.

### CODE REVIEW

**Comment by jvehent** [comment]
`Sorry, we could not display the entire diff because it was too big.`
Not the best tool to do this kind of review.... I went through everything until the net/http2 pkg, and it's all good

**Comment by jvehent** [comment]
@ameihm0912 take a look, just in case, and we can merge before building the next releases.

**Comment by jvehent** [comment]
```
$ git diff HEAD^1..HEAD | wc -l
31668
```
Thanksfully, it's mostly autogenerated code (the publicsuffix diff is gigantic).

**Comment by ameihm0912** [comment]
r+

**Comment by jvehent** [comment]
Feel free to merge it, I'm afk today.

**Pull request merged**
