### PR TITLE
WIP agent service refactoring

### PR DESCRIPTION
**Pull request by jvehent**
not functional, but for future ref

### CODE REVIEW

**Comment by robmurtha** [comment]
@jvehent can you please rebase this against the latest?

**Comment by jvehent** [comment]
@robmurtha No, I don't think we can rebase it without significant rewrite, unfortunately. This patch was a backup of work that was startup but never finished. :(

**Comment by ameihm0912** [comment]
@jvehent can this one be closed? This is a ways out of date as the agent service code has been refactored quite a bit.

**Comment by jvehent** [comment]
Totally, this is ancient.

**Pull request closed without merging**
