### PR TITLE
scribe updates for release

### PR DESCRIPTION
**Pull request by ameihm0912**
Not for immediate merge

This branch tracks changes related to the scribe module for the next MIG release; it currently contains a vendored downstream branch which will be removed prior to merge.

### CODE REVIEW

**Comment by jvehent** [comment]
Is the scribe update just a vendoring update with no change on mig's side?

**Comment by ameihm0912** [comment]
This should be largely a vendoring update, with some minor changes such as the changes in the pkg module. It's possible we may have a few others as I'm working on it at the moment, so wanted to keep them all together in this branch.

**Comment by ameihm0912** [comment]
@jvehent mind having a quick look at this? If it looks OK I'd like to merge so I can start some initial testing.

**Comment by jvehent** [comment]
Just realized travis-ci didn't run on this PR. This is odd, but I've add issues with travis being slow all day, so maybe it's related....

**Pull request merged**
